### ISSUE TITLE
CODE NOT WORKING AS EXPECTED

### ISSUE THREAD

**Issue by ghost** [Jtaim/Programming-Principles-and-Practice-Using-Cpp#4]
**Drill 9-11, Section 4** DOES NOT WORK AS EXPECTED.
The IF-Statement from line 89 is found outside the While-Loop, which causes a different output from intended. 

A solution to this will be to put the If-Statement into the While-Loop, just under the "std::cout << instructions << '\n';" line (84). 

Thanks.

**Comment by Jtaim** [comment]
inschools-ng - not sure this is an issue unless I am misunderstood something.  The if - statement checks to see if the vector container is not empty.  If the vector has stored converted measurement(s) values from the while loop then it will sort and then show the number of values in the vector, smallest value, largest value, and vector elements summed.  
The while loop stores all converted measurement in the vector and only exits when it receives a termination character.  Guess you could do the if statement inside the while and show the results of the vector elements every time but I left it last after gathering all the user input conversion. 
Thank you for the comment and let me know if i interpreted this wrong and if not I will close this comment.

**Comment by ghost** [comment]
Sorry for the late reply. I cross-checked the drill again and found out the problem was MY interpretation. 
When the loop ends, after receiving the termination key, the program prints the smallest and the largest number, the number of values, and the sum of values. Thanks a lot, especially for the repo.

**Comment by Jtaim** [comment]
If have any more questions please let me know.  I am by no means a fluent C++ developer and could learn from input. 
Thanks.
